sudo: required

services:
  - docker

script:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker build -t vrutkovs/gitrello . &&
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker push vrutkovs/gitrello;
    fi
